### ISSUE TITLE
 Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given

### ISSUE THREAD

**Issue by beeyev** [localheinz/composer-normalize#940]
If I try to use Phar version of the tool, I get this error. I assume that it's somehow connected to the bug which exists in a previous composer version. Here: https://github.com/composer/composer/issues/10907

````
composer-normalize composer.json 
PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in phar:///usr/local/bin/composer-normalize/vendor/composer/composer/src/Composer/Con
fig.php:193
Stack trace:
#0 phar:///usr/local/bin/composer-normalize/vendor/composer/composer/src/Composer/Config.php(193): array_merge(true, Array, true)
#1 phar:///usr/local/bin/composer-normalize/vendor/composer/composer/src/Composer/Factory.php(326): Composer\Config->merge(Array, './composer.json')
#2 phar:///usr/local/bin/composer-normalize/vendor/composer/composer/src/Composer/Factory.php(614): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), Array, true, '/var/w
ww/api', true, false)
#3 phar:///usr/local/bin/composer-normalize/vendor/composer/composer/src/Composer/Console/Application.php(469): Composer\Factory::create(Object(Composer\IO\ConsoleIO), NULL, true, fals
e)
#4 phar:///usr/local/bin/composer-normalize/vendor/composer/composer/src/Composer/Console/Application.php(411): Composer\Console\Application->getComposer(false, true)
#5 phar:///usr/local/bin/composer-normalize/vendor/composer/composer/src/Composer/Console/Application.php(352): Composer\Console\Application->hintCommonErrors(Object(TypeError), Object
(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/local/bin/composer-normalize/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(S
ymfony\Component\Console\Output\ConsoleOutput))
#7 phar:///usr/local/bin/composer-normalize/vendor/composer/composer/src/Composer/Console/Application.php(130): Symfony\Component\Console\Application->run(Object(Symfony\Component\Cons
ole\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/local/bin/composer-normalize/phar/composer-normalize.php(49): Composer\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#9 /usr/local/bin/composer-normalize(14): require('phar:///usr/loc...')
#10 {main}
  thrown in phar:///usr/local/bin/composer-normalize/vendor/composer/composer/src/Composer/Config.php on line 193
````

**Comment by localheinz** [comment]
Thank you for reporting, @beeyev!
